#!/usr/bin/python

import os
import sys


if len(sys.argv) != 2:
    print "USAGE: mycourse2clean <path>\n"  
    sys.exit(1)


path = sys.argv[1]
for filename in os.listdir(path):
    os.rename(os.path.join(path, filename), os.path.join(path, filename.split()[-1]))
